
services:
    irods-server:
      container_name: irods-server
      # image: "ghcr.io/wtsi-npg/ub-22.04-irods-4.3.2:latest"
      image: "wsinpg/ub-22.04-irods-4.3.3"
      platform: linux/amd64
      ports:
        - "127.0.0.1:1247:1247"
        - "127.0.0.1:20000-20199:20000-20199"
      restart: on-failure
      healthcheck:
        test: ["CMD", "nc", "-z", "-v", "127.0.0.1", "1247"]
        start_period: 30s
        interval: 5s
        timeout: 10s
        retries: 12

    app:
      build:
        context: .
        dockerfile: Dockerfile
      command: ["start",
                "--config", "/app/config/sqyrrl.toml",
                "--log-level", "trace"]
      # The following environment variables may be set in a .env file (files named .env
      # are declared in .gitignore):
      #
      # If using OIDC:
      #
      # OIDC_CLIENT_ID
      # OIDC_ISSUER_URL
      # OIDC_CALLBACK_URL
      #
      # The OIDC client secret may not be set in the environment. Instead, it should be
      # provided in the TOML config file mounted into the container at the path specified
      # by the --config option..
      env_file: .env
      ports:
        - "3333:3333"
      volumes:
        - ./server/testdata/config:/app/config
      depends_on:
        irods-server:
          condition: service_healthy
