Host = "0.0.0.0"
Port  = "3333"
IRODSEnvFilePath = "/app/config/app_irods_environment.json"
CertFilePath = "/app/config/localhost.crt"
KeyFilePath = "/app/config/localhost.key"
EnableOIDC  = true
OIDCClientID = ""
OIDCClientSecret = ""
OIDCIssuerURL = ""
OIDCRedirectURL = ""
IndexInterval = "60s"
